export const brands = [
  { name: "LG", src: "/assets/Index/2560px-LG_logo_2015.svg_.png" },
  { name: "Airwell", src: "/assets/Index/Airwell-logo.png" },
  { name: "Carrier", src: "/assets/Index/carrier-logo.png" },
  { name: "Daewoo", src: "/assets/Index/Daewoo_logo.svg_.png" },
  { name: "Daikin", src: "/assets/Index/Daikin-Logo.png" },
  { name: "Daitsu", src: "/assets/Index/daitsu-logo.com_.png" },
  { name: "Firstline", src: "/assets/Index/firstline-removebg-preview.png" },
  { name: "Fujitsu", src: "/assets/Index/Fujitsu-removebg-preview.png" },
  { name: "General Electric", src: "/assets/Index/general-electric-logo.com_.png" },
  { name: "General", src: "/assets/Index/general-logo-removebg-preview.png" },
  { name: "Goldstar", src: "/assets/Index/Goldstar_logotipo.svg_.png" },
  { name: "Haier", src: "/assets/Index/Haier-Logo-1984.png" },
  { name: "Haverland", src: "/assets/Marcas/haverland.png" },
  { name: "Hitecsa", src: "/assets/Index/Hitecsa_logo_01.png" },
  { name: "Johnson", src: "/assets/Index/johnson-banner-removebg-preview.png" },
  { name: "Lennox", src: "/assets/Index/Lennox-logo.png" },
  { name: "Fagor", src: "/assets/Index/logo-Fagor.png" },
  { name: "Hitachi", src: "/assets/Index/Logo-Hitachi.png" },
  { name: "Hiyasu", src: "/assets/Index/Logo-Hiyasu.png" },
  { name: "Midea", src: "/assets/Index/Midea-logo-1.png" },
  { name: "Mitsubishi Electric", src: "/assets/Index/Mitsubishi_Electric_logo.svg_.png" },
  { name: "Orbegozo", src: "/assets/Index/orbegozo-logo-1.png" },
  { name: "Panasonic", src: "/assets/Index/Panasonic_logo_Blue.svg_.png" },
  { name: "Roca", src: "/assets/Index/Roca-Logo.png" },
  { name: "Samsung", src: "/assets/Index/Samsung_Logo.svg_.webp" },
  { name: "Sanyo", src: "/assets/Index/Sanyo_logo.svg_.png" },
  { name: "Saunier Duval", src: "/assets/Index/Saunier-Duval-Logo-removebg-preview.png" },
  { name: "Toshiba", src: "/assets/Index/TOSHIBA_Logo.png" },
  { name: "York", src: "/assets/Index/york-logo.png" }
];
