export const brands = [
  { name: "LG", src: "/assets/Marcas/2560px-LG_logo_2015.svg_.png" },
  { name: "Airwell", src: "/assets/Marcas/Airwell-logo.png" },
  { name: "Carrier", src: "/assets/Marcas/carrier-logo.png" },
  { name: "Daewoo", src: "/assets/Marcas/Daewoo_logo.svg_.png" },
  { name: "Daikin", src: "/assets/Marcas/Daikin-Logo.png" },
  { name: "Daitsu", src: "/assets/Marcas/daitsu-logo.com_.png" },
  { name: "Firstline", src: "/assets/Marcas/firstline-removebg-preview.png" },
  { name: "Fujitsu", src: "/assets/Marcas/Fujitsu-removebg-preview.png" },
  { name: "General Electric", src: "/assets/Marcas/general-electric-logo.com_.png" },
  { name: "General", src: "/assets/Marcas/general-logo-removebg-preview.png" },
  { name: "Goldstar", src: "/assets/Marcas/Goldstar_logotipo.svg_.png" },
  { name: "Haier", src: "/assets/Marcas/Haier-Logo-1984.png" },
  { name: "Haverland", src: "/assets/Marcas/haverland.png" },
  { name: "Hitecsa", src: "/assets/Marcas/Hitecsa_logo_01.png" },
  { name: "Johnson", src: "/assets/Marcas/johnson-banner-removebg-preview.png" },
  { name: "Lennox", src: "/assets/Marcas/Lennox-logo.png" },
  { name: "Fagor", src: "/assets/Marcas/logo-Fagor.png" },
  { name: "Hitachi", src: "/assets/Marcas/Logo-Hitachi.png" },
  { name: "Hiyasu", src: "/assets/Marcas/Logo-Hiyasu.png" },
  { name: "Midea", src: "/assets/Marcas/Midea-logo-1.png" },
  { name: "Mitsubishi Electric", src: "/assets/Marcas/Mitsubishi_Electric_logo.svg_.png" },
  { name: "Orbegozo", src: "/assets/Marcas/orbegozo-logo-1.png" },
  { name: "Panasonic", src: "/assets/Marcas/Panasonic_logo_Blue.svg_.png" },
  { name: "Roca", src: "/assets/Marcas/Roca-Logo.png" },
  { name: "Samsung", src: "/assets/Marcas/Samsung_Logo.svg_.webp" },
  { name: "Sanyo", src: "/assets/Marcas/Sanyo_logo.svg_.png" },
  { name: "Saunier Duval", src: "/assets/Marcas/Saunier-Duval-Logo-removebg-preview.png" },
  { name: "Toshiba", src: "/assets/Marcas/TOSHIBA_Logo.png" },
  { name: "York", src: "/assets/Marcas/york-logo.png" }
];
