# Generated by Django 5.2.14 on 2026-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='obras/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('marcada_borrar', models.BooleanField(default=False)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyecto',
                'ordering': ['orden', 'subida_en'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(default='Plasencia, Cáceres', max_length=200)),
                ('coste', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('categoria', models.CharField(choices=[('reforma', 'Reforma'), ('obra', 'Obra'), ('destacado', 'Destacado')], default='reforma', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('imagen_antes', models.ImageField(blank=True, null=True, upload_to='obras/antes/')),
                ('imagen_despues', models.ImageField(blank=True, null=True, upload_to='obras/despues/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto de Obra',
                'verbose_name_plural': 'Proyectos de Obra',
                'ordering': ['-creado_en'],
            },
        ),
    ]
