# Generated by Django 5.2.14 on 2026-05-18 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono_prefijo', models.CharField(default='+34', max_length=8)),
                ('telefono_numero', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe tener exactamente 9 dígitos.', regex='^\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('poblacion', models.CharField(max_length=120)),
                ('trabajo_realizar', models.TextField()),
                ('tipo_reforma', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En revisión'), ('visita_programada', 'Visita técnica programada'), ('presupuesto_enviado', 'Presupuesto enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado')], default='recibido', max_length=30)),
                ('acepta_aviso_legal', models.BooleanField(default=False)),
                ('archivo_referencia', models.FileField(blank=True, null=True, upload_to='presupuestos/referencias/')),
                ('fecha_visita_tecnica', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Presupuesto',
                'verbose_name_plural': 'Solicitudes de Presupuesto',
                'ordering': ['-creado_en'],
            },
        ),
    ]
